%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: F:\work\sound_work\26112024_flies\fly_time.csv
%
% Auto-generated by MATLAB on 27-Nov-2024 16:08:11

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t_start", "t_end", "comment"];
opts.VariableTypes = ["datetime", "datetime", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "comment", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "t_start", "InputFormat", "HH:mm:ss.SSS");
opts = setvaropts(opts, "t_end", "InputFormat", "HH:mm:ss.SSS");

% Import the data
flytime = readtable("F:\work\sound_work\26112024_flies\fly_time.csv", opts);


%% Clear temporary variables
clear opts