function plot_pan_coords(filepath)
    filename = filepath+"pan_coord.csv";
    opts = detectImportOptions(filename);
    opts.VariableNames = ["lat", "lon","angle","name"];
    coords = readtable(filename,opts);
    geoplot(coords.lat, coords.lon, Marker="x", LineStyle="none", MarkerSize=14, Color="red", MarkerFaceColor="red");
    text(coords.lat(1), coords.lon(1), coords.name(1), ...
        'VerticalAlignment', 'bottom', ...
        'HorizontalAlignment', 'right', ...
        'Color', "white");
    text(coords.lat(2), coords.lon(2), coords.name(2), ...
        'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'left', ...
        'Color', "white");
    
    for i = 3:length(coords.name)
        text(coords.lat(i), coords.lon(i), coords.name(i), ...
            'VerticalAlignment', 'top', ...
            'HorizontalAlignment', 'right', ...
            'Color', "white", ...
            'Position', [coords.lat(i) coords.lon(i)+ (i-5)*1e-5]);
    end

    distance = 0.001;
    d = [distance * cos(deg2rad(coords.angle)), distance * sin(deg2rad(coords.angle))];
    q_pan = table(coords.lat, coords.lon, ...
        coords.lat + d(:,1), coords.lon + d(:,2), ...
        'VariableNames', {'lat_s', 'lon_s', 'lat_e', 'lon_e'});
    hold on
    for i = 1:length(q_pan.lat_s)
        geoplot([q_pan.lat_s(i), q_pan.lat_e(i)], ...
            [q_pan.lon_s(i), q_pan.lon_e(i)], ...
            'k', 'LineWidth', 2, 'MarkerSize', 5, Color = "y")
    end
    geobasemap satellite
    hold off
end

